### ISSUE TITLE
How to make this project from a clone?

### ISSUE THREAD

**Issue by traviswheeler** [deblasiolab/Opalv3#3]
I just cloned the repo, in hopes of running the newest opal, and found: 
(1) There were no instructions in the README for making the project from downloaded source.  I assume that's supposed to be "run `make`".  Doing so created class files in a bin directory, but did not create an Opal.jar file

(2) After running make, I tried to follow the README directions, and run `opal` ... but it doesn't exist. The executable `runopal` is there.  I'm guessing that's a remnant of having follow the directions at the bottom of the page for extracting source from the jar file (it involved moving `opal` to `runopal`, since the unjar command would unzip into a directory called `opal`

(3) Ok, so I ran `runopal`, and get the error 
```
java -server -Xmx1G -cp /Users/traviswheeler/git/Opalv3/ opal.Opal
Error: Could not find or load main class opal.Opal
```
That's because it really needs to point to where the class files went (the `bin` directory)
```
java -server -Xmx1G -cp /Users/traviswheeler/git/Opalv3/bin opal.Opal
```
Maybe it makes sense to just add the `/bin/` where the `cmd` variable is set?

I'm making this an issue instead of a PR, because I'm not sure if you have plans to maintain/extend this. Happy to chat about it.

**Comment by danfdeblasio** [comment]
Hey Travis, 

Thanks for catching these issues. We have been working on doing some bug-fixing (mostly to the parameter advising stuff). I should have put this stuff on a development branch since I hadn't updated the sort of "publically useable" version. I will try and address these ASAP and push an update. 

You're correct that most of the issues have to do with the separation of the code from the binaries, and since we don't end up using the JAR version I disabled its build for our development but its not a bad idea to put it back in. 

D

**Comment by danfdeblasio** [comment]
Hi Travis, 

Thanks for pointing out these items. I think I have corrected them all. You're right that the instructions were slop-ally transferred  from the v2 releases zip file. The `makefile` now recreated the `jar` and this is documented here as well as some changes to the documentation and the opal executable. Our summer project is to battle test all of the upgrades from v2 to make sure all works as expected, so hopefully there will be more improvements seen over the next couple months. 

Dan
